project:
  type: website

website:
  title: Muzhen Shen's personal webpage
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Bio

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto